services:
  mysql:
    image: mysql:8.0
    container_name: mysqldb
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=university_efficiency_db
      - MYSQL_USER=yuliia
      - MYSQL_PASSWORD=univchecker
      - MYSQL_ROOT_PASSWORD=root
  main-service:
    container_name: main_service
    build: ./
    volumes:
      - .m2:/root/.m2
      - ./:/Delivery
    ports:
      - "8081:8080"
    environment:
      SPRING_APPLICATION_JSON: '{
                "spring.datasource.url" : "jdbc:mysql://mysqldb:3306/university_efficiency_db?allowPublicKeyRetrieval=true&useSSL=false",
                "spring.datasource.username" : "yuliia",
                "spring.datasource.password" : "univchecker"
              }'
    depends_on:
      - mysql